eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

app:
  database:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    name: ${DB_NAME:logistics}

spring:
  datasource:
    username: ${DB_USERNAME:logistics}
    password: ${DB_PASSWORD:logistics}