eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

app:
  database:
    host: ${DB_HOST}
    port: ${DB_PORT:5432}
    name: ${DB_NAME:logistics}

spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
