server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${app.database.host}:${app.database.port}/${app.database.name}?currentSchema=users
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

jwt: # 테스트용 더미 값
  access-secret: ${JWT_ACCESS_SECRET:8Xn6SF+pB8BIodzuhKV+WCOJf+L+biGG4UD0Uch6fdA=}
  refresh-secret: ${JWT_REFRESH_SECRET:snNL4F2vawnUY+RM6t/IVloSZhrdHyKu96RV9c/h4kg=}
  cookie-secure: false
  access-token-expiration: 30m
  refresh-token-expiration: 14d

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true