spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          default-label: ${CONFIG_GIT_DEFAULT_LABEL:main}
          clone-on-start: true

management:
  tracing:
    export:
      zipkin:
        endpoint: ${ZIPKIN_ENDPOINT}
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.1}
