spring:
  application:
    name: notification-service

  profiles:
    default: local

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  datasource:
    url: jdbc:postgresql://localhost:5433/logistics

    username: ${USER_NAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8086

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

slack:
  bot-token: ${SLACK_BOT_TOKEN}
  base-url: https://slack.com/api
  channel-id: ${SLACK_CHANNEL_ID}

#Gemini API_KEY
gemini:
  api-key: ${GEMINI_API_KEY}
  base-url: https://generativelanguage.googleapis.com
  model: gemini-3.5-flash
