CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS hubs;
CREATE SCHEMA IF NOT EXISTS company_products;
CREATE SCHEMA IF NOT EXISTS deliveries;
CREATE SCHEMA IF NOT EXISTS orders;
CREATE SCHEMA IF NOT EXISTS notifications;
